### ISSUE TITLE
Alphabet Occurrence

### ISSUE THREAD

**Issue by amit-choudhary** [neha9t/basic-ruby#1]
Alphabet Occurrence:
fix spelling of occurrence 
in lib file name should be same as class name
you can call methods declared in string class directly on string eg ‘line.alphabet_occurrence’
incorrect method name..come up with a better name
indentation issues..anything in do..end block should be two spaces indented inside it
what is the need of calling inspect inside method..doesn’t make sense

**Comment by neha9t** [comment]
corrected!
1. fix spelling of occurence to occurrence
2. changed lib class to String
3. done
4. changed name to alphabet_count
5. corrected indentation issues 
6. done.

**Comment by amit-choudhary** [comment]
1. Fix naming
2. Remove explicit self.
3. Fix indentation.

**Comment by neha9t** [comment]
1. Renamed to alphabet_hash
2. Removed!
3. Fixed
